Pipeline 292 alex userassertions api
AtlasOfLivingAustralia/biocache-service pull request #591
Opened 2021-04-28 04:54 UTC by alexhuang091

- fixed apis to get/add/delete user assertions.
- Also changed `StoreDAO.get()` to return an `Optional` so anyone uses it should check if the return value is `null`

2021-05-04 13:13 UTC, djtfmartin commented
@alexhuang091 tests are still failing.

I suggest we convert this to draft until tests are fixed.

2021-05-04 13:14 UTC, djtfmartin requested changes
We need to fix tests

2021-05-05 00:36 UTC, alexhuang091 commented
> We need to fix tests

Hi Dave, the failures are in test cases for other code, not for assertion related code. I'll try to fix them.

2021-05-05 19:59 UTC, djtfmartin commented on src/main/java/au/org/ala/biocache/dto/QualityAssertion.java
> +        super();
Why the call to super() ?

2021-05-05 19:59 UTC, djtfmartin commented on src/main/java/au/org/ala/biocache/dto/QualityAssertion.java
> +        super();
Why the call to super() ?

2021-05-05 20:00 UTC, djtfmartin commented on src/main/java/au/org/ala/biocache/service/AssertionService.java
> +    // recordId + userId + code should be unique for normal assertions
Probably worth javadoc-ing this method, a description at the top

2021-05-05 20:01 UTC, djtfmartin commented on src/main/java/au/org/ala/biocache/util/OccurrenceUtils.java
>  //    private FullRecord[] getFullRecord(String uuid, SolrDocumentList result) {
Remove commented code

2021-05-05 20:01 UTC, djtfmartin commented on src/main/java/au/org/ala/biocache/util/OccurrenceUtils.java
>  //        Map<String, List<QualityAssertion>> assertions = new HashMap<String, List<QualityAssertion>>();
remove commented code

2021-05-05 20:03 UTC, djtfmartin commented on src/main/java/au/org/ala/biocache/web/OccurrenceController.java
> +                sd.addField("dbUserAssertions", assertions);
Is this `dbUserAssertions` field used ? Its not referenced elsewhere so I don't think it appears in any output

2021-05-05 20:04 UTC, djtfmartin approved these changes
thanks @alexhuang091 

Just minor things. Feel free to fix up and just merge without another review.

2021-05-06 00:39 UTC, merged